version: 0.2


phases:
  build:
    commands:
      - echo Entering the build phase
      - mvn clean package

  post_build:
    commands:
      - echo Build Completed Successfully
artifacts:
  files:
    - target/javaproject.jar
  discard-paths: yes